// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmoytmvsnemiakiahxzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtb3l0bXZzbmVtaWFraWFoeHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MzU5OTMsImV4cCI6MjA4NjQxMTk5M30.1alJUKzNAozfmgJJ5rIs-aYEO9h6m-zxIz1kr-BqW_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});